name: publish
on: [push]
jobs:
  publish-runpod-pytorch-nightly-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the runpod-pytorch-nightly Docker image
        run: |
          docker build . --tag ghcr.io/amadeuskkj/runpod-pytorch-nightly:latest
          docker push ghcr.io/amadeuskkj/runpod-pytorch-nightly:latest
